Repository ForUs-KW/NaviForYou_Backend, pull requests merged in 2024-01, with the labels that each got.

#4 Feat : Security , Swagger 기본 세팅
  build.gradle
  src/main/java/forus/naviforyou/NaviforyouApplication.java
  src/main/java/forus/naviforyou/global/common/BaseEntity.java
  src/main/java/forus/naviforyou/global/config/SecurityConfig.java
  src/main/java/forus/naviforyou/global/config/SwaggerConfig.java
  src/main/java/forus/naviforyou/global/error/handler/BaseExceptionHandler.java
Labels: 💫 feature, 💠 Sohyun

#2 Feat: 기본 엔티티 추가
  build.gradle
  src/main/java/forus/naviforyou/global/common/BaseEntity.java
  src/main/java/forus/naviforyou/global/common/entity/Accessibility.java
  src/main/java/forus/naviforyou/global/common/entity/Alter.java
  src/main/java/forus/naviforyou/global/common/entity/Building.java
  src/main/java/forus/naviforyou/global/common/entity/CustomizedAccessibility.java
  src/main/java/forus/naviforyou/global/common/entity/Member.java
  src/main/java/forus/naviforyou/global/common/entity/UserCustomized.java
  src/main/java/forus/naviforyou/global/common/entity/enums/MemberType.java
  src/main/java/forus/naviforyou/global/common/entity/enums/Role.java
  src/main/java/forus/naviforyou/global/error/handler/BaseExceptionHandler.java
Labels: 💫 feature, 💠 Changmin

#7 Fix : entity -> collection 전면 수정
  build.gradle
  src/main/java/forus/naviforyou/global/common/collection/alter/Alter.java
  src/main/java/forus/naviforyou/global/common/collection/building/Building.java
  src/main/java/forus/naviforyou/global/common/collection/building/Location.java
  src/main/java/forus/naviforyou/global/common/collection/building/UserReport.java
  src/main/java/forus/naviforyou/global/common/collection/enums/Accessibility.java
  src/main/java/forus/naviforyou/global/common/collection/enums/MemberType.java
  src/main/java/forus/naviforyou/global/common/collection/enums/Role.java
  src/main/java/forus/naviforyou/global/common/collection/member/Member.java
  src/main/java/forus/naviforyou/global/common/collection/member/UserAccessibility.java
  src/main/java/forus/naviforyou/global/common/entity/Accessibility.java
  src/main/java/forus/naviforyou/global/common/entity/Alter.java
  src/main/java/forus/naviforyou/global/common/entity/Building.java
  src/main/java/forus/naviforyou/global/common/entity/CustomizedAccessibility.java
  src/main/java/forus/naviforyou/global/common/entity/Member.java
  src/main/java/forus/naviforyou/global/common/entity/UserCustomized.java
  src/main/java/forus/naviforyou/global/common/entity/enums/Role.java
  src/test/java/forus/naviforyou/MongoDBTest/MongoDbRelationshipTest.java
  src/test/java/forus/naviforyou/MongoDBTest/repository/AccessibilityRepository.java
  src/test/java/forus/naviforyou/MongoDBTest/repository/AlterRepository.java
  src/test/java/forus/naviforyou/MongoDBTest/repository/BuildingRepository.java
  src/test/java/forus/naviforyou/MongoDBTest/repository/MemberRepository.java
  src/test/java/forus/naviforyou/MongoDBTest/repository/UserCustomizedRepository.java
Labels: 🐛 bug, ✅ test, 💠 Sohyun, 🔥 high priority

#10 Feat: 회원가입 및 로그인
  build.gradle
  src/main/java/forus/naviforyou/domain/member/controller/MemberController.java
  src/main/java/forus/naviforyou/domain/member/dto/request/LogInReq.java
  src/main/java/forus/naviforyou/domain/member/dto/request/SignUpReq.java
  src/main/java/forus/naviforyou/domain/member/dto/response/TokenRes.java
  src/main/java/forus/naviforyou/domain/member/repository/MemberRepository.java
  src/main/java/forus/naviforyou/domain/member/service/MemberService.java
  src/main/java/forus/naviforyou/global/common/Constants.java
  src/main/java/forus/naviforyou/global/common/collection/member/Member.java
  src/main/java/forus/naviforyou/global/common/service/CustomMemberDetailsService.java
  src/main/java/forus/naviforyou/global/config/SecurityConfig.java
  src/main/java/forus/naviforyou/global/config/jwt/JwtFilter.java
  src/main/java/forus/naviforyou/global/config/jwt/JwtTokenProvider.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
Labels: 💫 feature, 💠 Changmin

#18 Fix : 소셜 로그인 시큐리티 수정
  src/main/java/forus/naviforyou/domain/member/service/GoogleService.java
  src/main/java/forus/naviforyou/domain/member/service/NaverService.java
  src/main/java/forus/naviforyou/global/common/Constants.java
  src/main/java/forus/naviforyou/global/config/SecurityConfig.java
Labels: 🐛 bug, 💠 Sohyun

#19 Feat: 이메일 인증 기능 추가
  build.gradle
  src/main/java/forus/naviforyou/domain/member/controller/MemberController.java
  src/main/java/forus/naviforyou/domain/member/dto/request/CheckSingUpCodeReq.java
  src/main/java/forus/naviforyou/domain/member/service/MailService.java
  src/main/java/forus/naviforyou/domain/member/service/MemberService.java
  src/main/java/forus/naviforyou/global/common/Constants.java
  src/main/java/forus/naviforyou/global/common/service/RedisService.java
  src/main/java/forus/naviforyou/global/config/EmailConfig.java
  src/main/java/forus/naviforyou/global/config/RedisConfig.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
Labels: 💫 feature, 💠 Changmin

#20 Feat: 회원 가입 세부 로직 추가
  build.gradle
  src/main/java/forus/naviforyou/domain/member/controller/MemberController.java
  src/main/java/forus/naviforyou/domain/member/dto/request/CheckSingUpCodeReq.java
  src/main/java/forus/naviforyou/domain/member/dto/response/DuplicateRes.java
  src/main/java/forus/naviforyou/domain/member/repository/MemberRepository.java
  src/main/java/forus/naviforyou/domain/member/service/MailService.java
  src/main/java/forus/naviforyou/domain/member/service/MemberService.java
  src/main/java/forus/naviforyou/global/common/Constants.java
  src/main/java/forus/naviforyou/global/common/service/RedisService.java
  src/main/java/forus/naviforyou/global/config/EmailConfig.java
  src/main/java/forus/naviforyou/global/config/RedisConfig.java
  src/main/java/forus/naviforyou/global/config/SecurityConfig.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
Labels: 💫 feature, 💠 Changmin

#22 :recycle: Refactor: 인증 허용 URL 방식 변경 (#21)
  src/main/java/forus/naviforyou/global/common/Constants.java
  src/main/java/forus/naviforyou/global/config/SecurityConfig.java
  src/main/java/forus/naviforyou/global/config/jwt/JwtFilter.java
Labels: ♻️ refactor, 💠 Changmin

#23 Feat: 회원 추가 기능 구현
  src/main/java/forus/naviforyou/domain/member/controller/MemberController.java
  src/main/java/forus/naviforyou/domain/member/dto/request/ChangePwdReq.java
  src/main/java/forus/naviforyou/domain/member/dto/request/CheckCodeReq.java
  src/main/java/forus/naviforyou/domain/member/dto/response/DeleteRes.java
  src/main/java/forus/naviforyou/domain/member/service/MemberService.java
  src/main/java/forus/naviforyou/domain/myPage/controller/MyPageController.java
  src/main/java/forus/naviforyou/domain/myPage/dto/reponse/ResultRes.java
  src/main/java/forus/naviforyou/domain/myPage/dto/request/ChangePwdReq.java
  src/main/java/forus/naviforyou/domain/myPage/dto/request/DeleteReq.java
  src/main/java/forus/naviforyou/domain/myPage/dto/request/MyPageReq.java
  src/main/java/forus/naviforyou/domain/myPage/service/MyPageService.java
  src/main/java/forus/naviforyou/global/common/Constants.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
Labels: 💫 feature, 💠 Changmin
