Repository ForUs-KW/NaviForYou_Backend, pull requests merged in 2024-02, with the labels that each got.

#29 Feat: 장애인 편의시설 공공데이터 연동
  build.gradle
  src/main/java/forus/naviforyou/domain/place/controller/PlaceController.java
  src/main/java/forus/naviforyou/domain/place/dto/publicData/BuildingFacilityListDto.java
  src/main/java/forus/naviforyou/domain/place/dto/publicData/BuildingIdDto.java
  src/main/java/forus/naviforyou/domain/place/dto/request/ConvenientFacilityReq.java
  src/main/java/forus/naviforyou/domain/place/dto/response/BuildingFacilityListRes.java
  src/main/java/forus/naviforyou/domain/place/service/PlaceService.java
  src/main/java/forus/naviforyou/global/common/collection/building/Building.java
  src/main/java/forus/naviforyou/global/common/collection/building/UserReport.java
Labels: 💫 feature, 💠 Changmin

#28 Feat : 기본 길찾기 api 기능 구현
  src/main/java/forus/naviforyou/domain/findRoute/controller/FindRouteController.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/request/CarRouteReq.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/request/TravelRouteReq.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/request/WalkRouteReq.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/response/CarRouteRes.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/response/TravelRouteRes.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/response/WalkRouteRes.java
  src/main/java/forus/naviforyou/domain/findRoute/service/CarFindRouteService.java
  src/main/java/forus/naviforyou/domain/findRoute/service/TravelFindRouteService.java
  src/main/java/forus/naviforyou/domain/findRoute/service/WalkFindRouteService.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
Labels: 💫 feature, 💠 Sohyun

#36 Feat : swagger 문구 추가 완료
  src/main/java/forus/naviforyou/domain/findRoute/controller/FindRouteController.java
  src/main/java/forus/naviforyou/domain/member/controller/MemberController.java
  src/main/java/forus/naviforyou/domain/myPage/controller/MyPageController.java
  src/main/java/forus/naviforyou/domain/place/controller/PlaceController.java
  src/main/java/forus/naviforyou/domain/search/controller/SearchController.java
Labels: 💫 feature, ♻️ refactor, 💠 Sohyun

#43 Fix: 사용자 메일 인증 기능 오류 발생
  src/main/java/forus/naviforyou/domain/member/service/MemberService.java
Labels: 🐛 bug, 💠 Changmin, 🔥 high priority

#45 Fix : 소셜 로그인 일부 수정
  Jenkinsfile
  deploy/develop/script/deploy_server.sh
  deploy/develop/script/health_check.sh
  src/main/java/forus/naviforyou/domain/member/controller/MemberController.java
  src/main/java/forus/naviforyou/domain/member/service/GoogleService.java
  src/main/java/forus/naviforyou/domain/member/service/MemberService.java
  src/main/java/forus/naviforyou/domain/member/service/NaverService.java
  src/main/java/forus/naviforyou/global/HealthCheckController.java
Labels: 🐛 bug, 💠 Sohyun

#40 Feat : 실시간 버스/저상버스 정보 불러오기
  build.gradle
  src/main/java/forus/naviforyou/domain/realTime/controller/RealTimeController.java
  src/main/java/forus/naviforyou/domain/realTime/dto/request/BusStationReq.java
  src/main/java/forus/naviforyou/domain/realTime/dto/response/ItemList.java
  src/main/java/forus/naviforyou/domain/realTime/dto/response/ServiceResult.java
  src/main/java/forus/naviforyou/domain/realTime/service/BusService.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
Labels: 💫 feature, 💠 Sohyun

#53 Fix : return code status
  src/main/java/forus/naviforyou/domain/findRoute/service/TravelFindRouteService.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
  src/main/java/forus/naviforyou/global/error/exception/BaseException.java
  src/main/java/forus/naviforyou/global/error/handler/BaseExceptionHandler.java
Labels: 🐛 bug, 💠 Sohyun

#51 Feat : 거리순 검색 로직 추가
  src/main/java/forus/naviforyou/domain/search/controller/SearchController.java
  src/main/java/forus/naviforyou/domain/search/service/SearchService.java
Labels: 💫 feature, 💠 Sohyun

#37 Refactor : disabled 필터링 ( 계단 , 저상버스 고려 )
  src/main/java/forus/naviforyou/domain/findRoute/controller/FindRouteController.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/request/CarRouteReq.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/request/TravelRouteReq.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/request/WalkRouteReq.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/response/CarRouteRes.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/response/TravelRouteRes.java
  src/main/java/forus/naviforyou/domain/findRoute/dto/response/WalkRouteRes.java
  src/main/java/forus/naviforyou/domain/findRoute/service/TravelFindRouteService.java
  src/main/java/forus/naviforyou/domain/findRoute/service/WalkFindRouteService.java
  src/main/java/forus/naviforyou/domain/member/service/NaverService.java
  src/main/java/forus/naviforyou/domain/realTime/controller/RealTimeController.java
  src/main/java/forus/naviforyou/domain/realTime/dto/request/BusStationReq.java
  src/main/java/forus/naviforyou/domain/realTime/service/BusService.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
Labels: 💫 feature, ♻️ refactor, 💠 Sohyun

#62 Feat: 지하철 실시간 위치 정보
  src/main/java/forus/naviforyou/domain/findRoute/service/TravelFindRouteService.java
  src/main/java/forus/naviforyou/domain/place/controller/PlaceController.java
  src/main/java/forus/naviforyou/domain/place/dto/publicData/SubwayDto.java
  src/main/java/forus/naviforyou/domain/place/dto/publicData/SubwayInfoListDto.java
  src/main/java/forus/naviforyou/domain/place/dto/response/SubwayRealTimeRes.java
  src/main/java/forus/naviforyou/domain/place/service/PlaceService.java
  src/main/java/forus/naviforyou/global/config/CorsConfig.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
  src/main/java/forus/naviforyou/global/error/exception/BaseException.java
  src/main/java/forus/naviforyou/global/error/handler/BaseExceptionHandler.java
Labels: 💫 feature, 💠 Changmin

#55 Feat: 기존 네이버 지역 API -> 티맵 POI API 변경
  src/main/java/forus/naviforyou/domain/place/controller/PlaceController.java
  src/main/java/forus/naviforyou/domain/place/dto/request/BuildingInfoReq.java
  src/main/java/forus/naviforyou/domain/place/dto/tmap/PoiBuildingInfo.java
  src/main/java/forus/naviforyou/domain/place/service/PlaceService.java
  src/main/java/forus/naviforyou/domain/search/controller/SearchController.java
  src/main/java/forus/naviforyou/domain/search/dto/request/SearchReq.java
  src/main/java/forus/naviforyou/domain/search/dto/response/Item.java
  src/main/java/forus/naviforyou/domain/search/dto/response/SearchRes.java
  src/main/java/forus/naviforyou/domain/search/service/SearchService.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
Labels: 💫 feature, ♻️ refactor, 💠 Changmin

#56 Refactor: 건물 정보에 장애인 편의 시설 정보 반영
  src/main/java/forus/naviforyou/domain/member/service/MailService.java
  src/main/java/forus/naviforyou/domain/place/controller/PlaceController.java
  src/main/java/forus/naviforyou/domain/place/dto/publicData/BuildingIdDto.java
  src/main/java/forus/naviforyou/domain/place/dto/request/LocationReq.java
  src/main/java/forus/naviforyou/domain/place/dto/response/BuildingInfoRes.java
  src/main/java/forus/naviforyou/domain/place/dto/response/LocationRes.java
  src/main/java/forus/naviforyou/domain/place/service/PlaceService.java
  src/main/java/forus/naviforyou/domain/search/dto/request/SearchReq.java
  src/main/java/forus/naviforyou/domain/search/dto/response/SearchRes.java
  src/main/java/forus/naviforyou/domain/search/service/SearchService.java
  src/main/java/forus/naviforyou/global/common/Constants.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
Labels: ♻️ refactor, 💠 Changmin

#63 Feat: 지하철 API EndPoint 변경
  src/main/java/forus/naviforyou/domain/place/controller/PlaceController.java
Labels: 💫 feature, 💠 Changmin

#65 Feat: 비밀번호 찾기 시 인증 이메일 회원가입 여부 확인
  src/main/java/forus/naviforyou/domain/member/service/MemberService.java
  src/main/java/forus/naviforyou/global/error/dto/ErrorCode.java
Labels: 🐛 bug, 💠 Changmin

#66 Fix: CORS ERORR
  src/main/java/forus/naviforyou/global/config/SecurityConfig.java
Labels: 🐛 bug, 💠 Changmin, 🔥 high priority

#68 Chore : cicd fin.
  Jenkinsfile
  deploy/develop/script/deploy_server.sh
  src/main/java/forus/naviforyou/global/HealthCheckController.java
Labels: 🐛 bug, 🗃 infra, 💠 Changmin, 💠 Sohyun
